# Generated by Django 5.2.1 on 2025-05-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingrecord',
            old_name='parking_sport',
            new_name='parking_spot',
        ),
    ]
